// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOtq88OnAdG3O-xiMfQljdS-neoML8Ac4',
    appId: '1:316580956209:web:992385c685ec112ade2d10',
    messagingSenderId: '316580956209',
    projectId: 'hanpanhae',
    authDomain: 'hanpanhae.firebaseapp.com',
    storageBucket: 'hanpanhae.firebasestorage.app',
    measurementId: 'G-FGQ6EBLQ5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt_pH-Q_r26hi9MdkpRcH1x0VHN70ytys',
    appId: '1:316580956209:android:ee0ac46a1e8ab1f5de2d10',
    messagingSenderId: '316580956209',
    projectId: 'hanpanhae',
    storageBucket: 'hanpanhae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyPWwC6vOhBz3botC-b2YSV9ANV8eKxHA',
    appId: '1:316580956209:ios:41f6d6e099d55125de2d10',
    messagingSenderId: '316580956209',
    projectId: 'hanpanhae',
    storageBucket: 'hanpanhae.firebasestorage.app',
    iosBundleId: 'com.example.hanpanhae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyPWwC6vOhBz3botC-b2YSV9ANV8eKxHA',
    appId: '1:316580956209:ios:41f6d6e099d55125de2d10',
    messagingSenderId: '316580956209',
    projectId: 'hanpanhae',
    storageBucket: 'hanpanhae.firebasestorage.app',
    iosBundleId: 'com.example.hanpanhae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOtq88OnAdG3O-xiMfQljdS-neoML8Ac4',
    appId: '1:316580956209:web:8805e747b775faf3de2d10',
    messagingSenderId: '316580956209',
    projectId: 'hanpanhae',
    authDomain: 'hanpanhae.firebaseapp.com',
    storageBucket: 'hanpanhae.firebasestorage.app',
    measurementId: 'G-1JJ3WWZ0CM',
  );
}
